<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>17114954-f94f-4b9f-887d-871dba37a612</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Properties\launchSettings.json" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Asp.Versioning.Mvc.ApiExplorer" Version="10.0.0" />
    <PackageReference Include="Microsoft.OpenApi" Version="1.6.14" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="10.0.2" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.9.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Practical23.BAL\Practical23.BAL.csproj" />
    <ProjectReference Include="..\Practical23.DAL\Practical23.DAL.csproj" />
    <ProjectReference Include="..\Practical23.Domain\Practical23.Domain.csproj" />
  </ItemGroup>

</Project>
